config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  draw :api
  draw :web

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord
  encrypts :company, :billing_to

  belongs_to :user

  has_many :invoice_emails, dependent: :delete_all
  accepts_nested_attributes_for :invoice_emails, allow_destroy: true

  validates :issue_date, :company, :billing_to, :total_value_cents, presence: true

  monetize :total_value_cents
end

app/models/invoice_email.rb
# frozen_string_literal: true

class InvoiceEmail < ApplicationRecord
  encrypts :email, deterministic: true

  belongs_to :invoice

  validates :email,
            presence: true,
            uniqueness: {
              case_sensitive: false,
              scope: :invoice_id,
              message: 'Each email must be unique per invoice'
            },
            format: { with: ::URI::MailTo::EMAIL_REGEXP }

  normalizes :email, with: ->(value) { value.strip }
end

app/models/invoices/create.rb
# frozen_string_literal: true

module Invoices
  class Create < ::Micro::Case
    attribute :issue_date, validates: { kind: ::Kind::String }
    attribute :company, validates: { kind: ::Kind::String }
    attribute :billing_to, validates: { kind: ::Kind::String }
    attribute :total_value, validates: { kind: ::Kind::String }
    attribute :invoice_emails_attributes, validates: { kind: ::Kind::Hash }
    attribute :user_id, validates: { kind: ::Kind::String }

    def call!
      create_invoice
    end

    private

    # rubocop:disable Metrics/MethodLength
    def create_invoice
      invoice = ::Invoice.new(
        issue_date:,
        company:,
        billing_to:,
        total_value:,
        invoice_emails_attributes:,
        user_id:
      )

      invoice.save

      return Failure(:invalid, result: { invoice: }) unless invoice.valid?

      Success(:ok, result: { invoice: })
    rescue ActiveRecord::RecordNotUnique
      invoice.errors.add(:base, 'Each email must be unique per invoice')

      Failure(:invalid, result: { invoice: })
    end
    # rubocop:enable Metrics/MethodLength
  end
end

app/models/invoices/list.rb
# frozen_string_literal: true

module Invoices
  class List < ::Micro::Case
    attribute :user_id, validates: { kind: ::Kind::String }
    attribute :filters, validates: { kind: ::Kind::Hash }

    def call!
      remove_blank_filters
        .then(:find_invoices)
    end

    private

    RemoveBlankValue = ->(_, value) { value.blank? }

    def remove_blank_filters
      filters.reject!(&RemoveBlankValue)

      Success(:ok)
    end

    def find_invoices
      invoices = ::Invoice.where(user_id:)
      invoices = invoices.where(**filters) if filters.present?
      invoices = invoices.order(:issue_date)

      Success(:ok, result: { invoices: })
    end
  end
end

app/models/invoices/pdf/export.rb
# frozen_string_literal: true

module Invoices
  module Pdf
    class Export < ::Micro::Case
      attribute :invoice_id, validates: { kind: ::Kind::String }
      attribute :user_id, validates: { kind: ::Kind::String }

      def call!
        find_invoice
          .then(:generate_pdf)
      end

      private

      def find_invoice
        invoice = ::Invoice.find_by(id: invoice_id, user_id:)

        return Failure(:invoice_not_found) unless invoice

        Success(:ok, result: { invoice: })
      end

      def generate_pdf(invoice:, **)
        pdf = Generator.call(invoice:)

        Success(:ok, result: { pdf: })
      end
    end
  end
end

app/models/invoices/pdf/generate_tempfile.rb
# frozen_string_literal: true

module Invoices
  module Pdf
    class GenerateTempfile < ::Micro::Case
      attribute :invoice_id, validates: { kind: ::Kind::String }

      def call!
        find_invoice
          .then(:generate_temp_pdf)
      end

      private

      def find_invoice
        invoice = ::Invoice.find_by(id: invoice_id)

        return Failure(:invoice_not_found) unless invoice

        Success(:ok, result: { invoice: })
      end

      def generate_temp_pdf(invoice:, **)
        pdf = Generator.call(invoice:)

        temp_pdf = Tempfile.new(["invoice_#{invoice.id}", '.pdf'], Rails.root.join('tmp'))
        pdf.render_file(temp_pdf.path)

        Success(:ok, result: { invoice:, pdf_path: temp_pdf.path })
      end
    end
  end
end

app/models/invoices/pdf/generator.rb
# frozen_string_literal: true

module Invoices
  module Pdf
    class Generator
      def self.call(invoice:, builder: Prawn::Document.new)
        builder.text "Invoice ##{invoice.id}"
        builder.text "Issue date: #{invoice.issue_date}"
        builder.text "Company: #{invoice.company}"
        builder.text "Billing to: #{invoice.billing_to}"
        builder.text "Total value: #{invoice.total_value}"
        builder
      end
    end
  end
end

app/models/invoices/public_display.rb
# frozen_string_literal: true

module Invoices
  class PublicDisplay < ::Micro::Case
    attribute :invoice_id, validates: { kind: ::Kind::String }

    def call!
      find_invoice
    end

    private

    def find_invoice
      invoice = ::Invoice.find_by(id: invoice_id)

      return Failure(:invoice_not_found) unless invoice

      Success(:ok, result: { invoice: })
    end
  end
end

app/models/invoices/show.rb
# frozen_string_literal: true

module Invoices
  class Show < ::Micro::Case
    attribute :invoice_id, validates: { kind: ::Kind::String }
    attribute :user_id, validates: { kind: ::Kind::String }

    def call!
      find_invoice
    end

    private

    def find_invoice
      invoice = ::Invoice.find_by(id: invoice_id, user_id:)

      return Failure(:invoice_not_found) unless invoice

      Success(:ok, result: { invoice: })
    end
  end
end

app/controllers/api/v1/invoices_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class InvoicesController < ApplicationController
      include ::Pagy::Backend

      before_action :authenticate

      # rubocop:disable Metrics/MethodLength
      # rubocop:disable Metrics/AbcSize
      def index
        pagination_options = {
          page: params[:page],
          items: params[:items] || 10
        }

        input = {
          user_id: current_user.id,
          filters: {
            issue_date: params[:issue_date],
            invoice_number: params[:invoice_number]
          }
        }

        ::Invoices::List.call(input) do |on|
          on.success { render_invoices(_1[:invoices], pagination_options) }
          on.unknown { raise _1.inspect.errors }
        end
      end
      # rubocop:enable Metrics/MethodLength
      # rubocop:enable Metrics/AbcSize

      # rubocop:disable Metrics/MethodLength
      # rubocop:disable Metrics/AbcSize
      def create
        input = {
          issue_date: invoice_params[:issue_date],
          company: invoice_params[:company],
          billing_to: invoice_params[:billing_to],
          total_value: invoice_params[:total_value],
          invoice_emails_attributes: invoice_params[:invoice_emails_attributes],
          user_id: current_user.id
        }

        ::Invoices::Create.call(input) do |on|
          on.success do
            generate_invoice_pdf(_1[:invoice])
            render_invoice(_1[:invoice])
          end
          on.failure(:invalid) { render_invoice_errors(_1[:invoice]) }
          on.unknown { raise _1.inspect.errors }
        end
      end
      # rubocop:enable Metrics/MethodLength
      # rubocop:enable Metrics/AbcSize

      def show
        input = {
          invoice_id: params[:id],
          user_id: current_user.id
        }

        ::Invoices::Show.call(input) do |on|
          on.success { render_invoice(_1[:invoice]) }
          on.failure(:invoice_not_found) { render_not_found }
          on.unknown { raise _1.inspect.errors }
        end
      end

      private

      def invoice_params
        params.require(:invoice).permit(:issue_date, :company, :billing_to, :total_value,
                                        invoice_emails_attributes: %i[id email _destroy])
      end

      def generate_invoice_pdf(invoice)
        ::Invoices::Pdf::GenerateTempfileJob.perform_later(invoice.id)
      end

      def render_invoices(invoices, pagination_options)
        pagy, invoices = pagy(invoices, **pagination_options)

        render json: {
          invoices:,
          pagination: {
            page: pagy.page,
            items: pagy.items,
            count: pagy.count,
            pages: pagy.pages
          }
        }
      end

      def render_invoice(invoice)
        render json: invoice, status: :ok
      end

      def render_invoice_errors(invoice)
        render json: { errors: invoice.errors }, status: :unprocessable_entity
      end

      def render_not_found
        error_message = {
          error: 'Not Found',
          message: 'The requested invoice could not be found.'
        }

        render json: error_message, status: :not_found
      end
    end
  end
end

app/controllers/invoices/pdf_exports_controller.rb
# frozen_string_literal: true

module Invoices
  class PdfExportsController < ::ApplicationController
    before_action :authenticate_user!

    def show
      input = {
        invoice_id: params[:id],
        user_id: ::Current.user.id
      }

      Pdf::Export.call(input) do |on|
        on.success { render_pdf(_1[:pdf]) }
        on.failure(:invoice_not_found) { return_not_found }
        on.unknown { raise _1.inspect.errors }
      end
    end

    private

    def return_not_found
      head :not_found
    end

    def render_pdf(pdf)
      respond_to do |format|
        format.pdf do
          send_data pdf.render, filename: 'invoice.pdf',
                                type: 'application/pdf',
                                disposition: 'inline'
        end
      end
    end
  end
end

app/controllers/invoices/public_displays_controller.rb
# frozen_string_literal: true

module Invoices
  class PublicDisplaysController < ::ApplicationController
    def show
      input = {
        invoice_id: params[:id]
      }

      PublicDisplay.call(input) do |on|
        on.success { render_invoice(_1[:invoice]) }
        on.failure(:invoice_not_found) { redirect_to_root_path }
        on.unknown { raise _1.inspect.errors }
      end
    end

    private

    def render_invoice(invoice)
      render 'invoices/show', locals: { invoice: }
    end

    def redirect_to_root_path
      redirect_to root_path, alert: 'Invoice not found'
    end
  end
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

class InvoicesController < ::ApplicationController
  include ::Pagy::Backend

  before_action :authenticate_user!

  def new
    invoice = ::Invoice.new
    invoice.invoice_emails.build

    render 'invoices/new', locals: { invoice: }
  end

  # rubocop:disable Metrics/MethodLength
  # rubocop:disable Metrics/AbcSize
  def create
    input = {
      issue_date: invoice_params[:issue_date],
      company: invoice_params[:company],
      billing_to: invoice_params[:billing_to],
      total_value: invoice_params[:total_value],
      invoice_emails_attributes: invoice_params[:invoice_emails_attributes],
      user_id: ::Current.user.id
    }

    ::Invoices::Create.call(input) do |on|
      on.success do
        generate_invoice_pdf(_1[:invoice])
        redirect_invoice(_1[:invoice])
      end
      on.failure(:invalid) { render_form_errors(_1[:invoice]) }
      on.unknown { raise _1.inspect.errors }
    end
  end
  # rubocop:enable Metrics/MethodLength
  # rubocop:enable Metrics/AbcSize

  # rubocop:disable Metrics/MethodLength
  def index
    input = {
      user_id: ::Current.user.id,
      filters: {
        issue_date: params[:issue_date],
        invoice_number: params[:invoice_number]
      }
    }

    ::Invoices::List.call(input) do |on|
      on.success { render_invoices(_1[:invoices]) }
      on.unknown { raise _1.inspect.errors }
    end
  end
  # rubocop:enable Metrics/MethodLength

  def show
    input = {
      invoice_id: params[:id],
      user_id: ::Current.user.id
    }

    ::Invoices::Show.call(input) do |on|
      on.success { render_invoice(_1[:invoice]) }
      on.failure(:invoice_not_found) { render_not_found }
      on.unknown { raise _1.inspect.errors }
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:issue_date, :company, :billing_to, :total_value,
                                    invoice_emails_attributes: %i[id email _destroy])
  end

  def render_invoices(invoices)
    pagy, invoices = pagy(invoices, items: 10, link_extra: 'data-turbo-action="advance"')

    render 'invoices/index', locals: { invoices:, pagy: }
  end

  def render_invoice(invoice)
    render 'invoices/show', locals: { invoice: }
  end

  def render_not_found
    flash[:alert] = 'Invoice not found'

    redirect_to invoices_path, status: :found
  end

  def redirect_invoice(invoice)
    flash[:success] = 'Invoice was successfully created'

    redirect_to invoice_path(invoice), status: :found
  end

  def render_form_errors(invoice)
    render 'invoices/new', locals: { invoice: }, status: :unprocessable_entity
  end

  def generate_invoice_pdf(invoice)
    ::Invoices::Pdf::GenerateTempfileJob.perform_later(invoice.id)
  end
end

app/helpers/invoices_helper.rb
# frozen_string_literal: true

module InvoicesHelper
  include ::Pagy::Frontend

  def invoice_number_formatter(number)
    number.to_s.rjust(4, '0')
  end
end

app/views/invoices/_email.html.erb
<div class="field">
  <%= fields_for "invoice[invoice_emails_attributes][#{invoice_email.object_id}]", invoice_email do |ff| %>
    <%= ff.label :email, class: 'label' %>
    <%= ff.text_field :email, class: 'input', required: true %>
  <% end %>
</div>

app/views/invoices/_no_invoices.html.erb
<section class="section">
  <div class="container has-text-centered">
    <p class="title is-3">No invoices found.</p>
  </div>
</section>

app/views/invoices/email_field.html.erb
<%= render partial: "email", locals: { invoice_email: ::InvoiceEmail.new } %>

app/views/invoices/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Invoices</h1>

    <div class="field is-grouped is-grouped-right">
      <%= link_to 'New Invoice', new_invoice_path, class: "button is-primary" %>
    </div>

    <%= form_with(url: invoices_path, method: :get,
        data: {
          turbo_frame: "invoices",
          turbo_action: "advance",
          controller: "form",
          action: "input->form#submit"
        }, class: "box") do |form| %>
      <div class="columns is-multiline is-align-items-flex-end">
        <div class="column is-4">
          <div class="field">
            <%= form.label :issue_date, "Issue Date" %>
            <%= form.date_field :issue_date, class: "input" %>
          </div>
        </div>
        <div class="column is-4">
          <div class="field">
            <%= form.label :invoice_number, "Invoice Number" %>
            <%= form.text_field :invoice_number, class: "input" %>
          </div>
        </div>
        <div class="column is-4">
          <div class="field is-grouped ">
            <div class="control">
              <%= form.submit "Filter", class: "button" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= turbo_frame_tag "invoices", autoscroll: true, data: { autoscroll_block: "start" }  do %>
      <% if invoices.any? %>
        <table class="table is-fullwidth is-striped">
          <thead>
            <tr>
              <th class="has-text-centered">Number</th>
              <th class="has-text-centered">Issue Date</th>
              <th class="has-text-centered">Company</th>
              <th class="has-text-centered">Total Value</th>
            </tr>
          </thead>
          <tbody>
            <% invoices.each do |invoice| %>
              <tr>
                <td class="has-text-centered"><%= invoice_number_formatter(invoice.invoice_number) %></td>
                <td class="has-text-centered"><%= invoice.issue_date %></td>
                <td class="has-text-centered"><%= invoice.company %></td>
                <td class="has-text-centered"><%= number_to_currency(invoice.total_value) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <% if pagy.pages > 1 %>
          <div class="pagy-nav">
            <%== pagy_bulma_nav(pagy) %>
          </div>
        <% end %>
      <% else %>
        <% render "invoices/no_invoices" %>
      <% end %>
    <% end %>
  </div>
</section>

app/views/invoices/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">New Invoice</h1>

    <%= form_with(model: invoice, method: :post,
          data: {
            controller: "form",
            action: "input->form#submit"
          }) do |form| %>

      <% if invoice.errors.any? %>
        <article class="message is-danger">
          <div class="message-header">
            <p><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</p>
          </div>
          <div class="message-body">
            <ul>
              <% invoice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </article>
      <% end %>

      <div class="field">
        <%= form.label :issue_date, class: 'label' %>
        <%= form.date_field :issue_date, class: 'input', required: true %>
      </div>

      <div class="field">
        <%= form.label :company, class: 'label' %>
        <%= form.text_field :company, class: 'input', required: true %>
      </div>

      <div class="field">
        <%= form.label :billing_to, class: 'label' %>
        <%= form.text_area :billing_to, class: 'input', required: true %>
      </div>

      <div class="field">
        <%= form.label :total_value, class: 'label' %>
        <%= form.text_field :total_value, class: 'input' %>
      </div>

      <div class="field">
        <div id="invoice-emails">
          <%= render partial: 'email', collection: invoice.invoice_emails, as: :invoice_email %>
        </div>
        <%= link_to 'Add another email', new_invoice_email_path, data: { turbo_stream: true }, class: "button mt-4" %>
      </div>

      <%= form.submit 'Submit', class: 'button is-primary' %>
    <% end %>
  </div>
</section>

app/views/invoices/show.html.erb
<%= turbo_frame_tag "invoices" do %>
  <article class="message is-primary">
    <div class="message-header">
      <p>Invoice Details</p>
      <%= link_to 'Download PDF', invoices_pdf_export_path(invoice, format: :pdf),
                  class: 'button is-small is-light',
                  target: '_blank' %>
    </div>
    <div class="message-body content">
      <p><strong>Issue Date:</strong> <%= invoice.issue_date %></p>
      <p><strong>Company:</strong> <%= invoice.company %></p>
      <p><strong>Billing To:</strong> <%= invoice.billing_to %></p>
      <p><strong>Total Value:</strong> <%= number_to_currency(invoice.total_value) %></p>

      <% if ::Current.user %>
        <% if invoice.invoice_emails.any? %>
          <div class="email-list">
            <strong>Emails:</strong>
            <ul>
              <% invoice.invoice_emails.each do |invoice_email| %>
                <li><%= invoice_email.email %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  </article>
<% end %>